services:
  - type: web
    name: hindi-ocr-flask
    env: python
    build:
      pythonVersion: 3.8
    buildCommand: pip install -r src/requirements.txt
    startCommand: gunicorn upload:app --chdir src
    autoDeploy: true
